# install.ps1 - unpack the RAG bundle on Windows.
# Run from the unzipped bundle folder (double-click install.bat, or right-click -> Run with PowerShell).

$ErrorActionPreference = "Stop"
$BundleRoot = $PSScriptRoot
Set-Location $BundleRoot

Write-Host ""
Write-Host "=== local-rag Windows installer ==="
Write-Host "Bundle root: $BundleRoot"
Write-Host ""

$UvExe = Join-Path $BundleRoot "bin\uv.exe"
if (-not (Test-Path $UvExe)) {
    Write-Error "bin\uv.exe not found in bundle. Bundle is corrupt."
    exit 1
}

$SourceDir = Join-Path $BundleRoot "source"
if (-not (Test-Path $SourceDir)) {
    Write-Error "source\ directory not found in bundle. Bundle is corrupt."
    exit 1
}

# 1. Sync Python dependencies into source\.venv using the bundled uv.
Write-Host "[1/3] Installing Python dependencies into source\.venv via bundled uv..."
Push-Location $SourceDir
try {
    & $UvExe sync
    if ($LASTEXITCODE -ne 0) { throw "uv sync failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}
Write-Host "      done."
Write-Host ""

# 2. Write .env with bundle-absolute paths.
$MemoryDb      = Join-Path $BundleRoot "data\memory.db"
$ExtensionsDir = Join-Path $BundleRoot "data\extensions"
# Pick the first .gguf file inside data\models\.
$ModelFile = Get-ChildItem -Path (Join-Path $BundleRoot "data\models") -Filter "*.gguf" | Select-Object -First 1
if (-not $ModelFile) {
    Write-Error "No .gguf file found in data\models. Bundle is corrupt."
    exit 1
}
$ModelPath = $ModelFile.FullName

$EnvPath = Join-Path $SourceDir ".env"
$EnvContent = @"
# Auto-generated by install.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm').
# NOTES_DIR is ignored by server.py (Windows never ingests) — placeholder only.
NOTES_DIR=C:\notes-placeholder
MEMORY_DB=$MemoryDb
EXTENSIONS_DIR=$ExtensionsDir
MODEL_PATH=$ModelPath

MEMORY_VECTOR_WEIGHT=0.5
MEMORY_TEXT_WEIGHT=0.5
MEMORY_MAX_RESULTS=10
MEMORY_MIN_SCORE=0.6
"@

Write-Host "[2/3] Writing $EnvPath..."
Set-Content -Path $EnvPath -Value $EnvContent -Encoding utf8
Write-Host "      done."
Write-Host ""

# 3. Register the MCP server in Claude Desktop's config.
Write-Host "[3/3] Registering MCP server in %APPDATA%\Claude\claude_desktop_config.json..."
Push-Location $SourceDir
try {
    & $UvExe run python -m setup.install_claude_desktop --uv "$UvExe" --project-dir "$SourceDir"
    if ($LASTEXITCODE -ne 0) { throw "install_claude_desktop failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}
Write-Host ""
Write-Host "Installation complete. Restart Claude Desktop to load the MCP server."
