r"""Build a self-contained Windows distribution bundle (ZIP) of the RAG project.

Run on macOS after a successful ingest. The resulting ZIP contains:

    rag-bundle-YYYY-MM-DD-HHMM/
      source/                           # server.py, ingest.py, setup/, pyproject.toml, uv.lock, ...
      data/
        memory.db                       # copied from <project>/data/memory.db
        models/*.gguf                   # copied from <project>/data/models/
        extensions/{vector,memory}.dll  # downloaded fresh for Windows
      bin/
        uv.exe                          # portable uv for Windows (no install needed)
      install.ps1
      install.bat
      README-windows.md
      manifest.json                     # SHA256 of every file

The user runs `install.bat` on Windows — it unpacks deps into a local `.venv`
via the bundled uv.exe, writes `.env` with bundle-absolute paths, and
auto-registers the MCP server in `%APPDATA%\Claude\claude_desktop_config.json`.

No admin rights, no external downloads, no PATH mutation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tarfile
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from setup._http import stream_download
from setup.download_extensions import (
    MEMORY_ASSETS,
    MEMORY_URL_TEMPLATE,
    MEMORY_VERSION,
    VECTOR_ASSETS,
    VECTOR_URL_TEMPLATE,
    VECTOR_VERSION,
)


DEFAULT_UV_VERSION = "0.11.7"
UV_ASSET = "uv-x86_64-pc-windows-msvc.zip"
UV_URL_TEMPLATE = "https://github.com/astral-sh/uv/releases/download/{version}/{asset}"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DIST_DIR = PROJECT_ROOT / "dist"

# Files/dirs copied verbatim from <project>/ into bundle/source/.
SOURCE_FILES = [
    "server.py",
    "ingest.py",
    "pyproject.toml",
    "uv.lock",
    ".env.example",
    "claude_desktop_config.example.json",
    "README.md",
]
SOURCE_DIRS = ["setup"]


# ---------------------------------------------------------------------------
# Installer + README templates (embedded so the bundle is self-contained).
# ---------------------------------------------------------------------------

INSTALL_PS1 = r"""# install.ps1 - unpack the RAG bundle on Windows.
# Run from the unzipped bundle folder (double-click install.bat, or right-click -> Run with PowerShell).

$ErrorActionPreference = "Stop"
$BundleRoot = $PSScriptRoot
Set-Location $BundleRoot

Write-Host ""
Write-Host "=== local-rag Windows installer ==="
Write-Host "Bundle root: $BundleRoot"
Write-Host ""

$UvExe = Join-Path $BundleRoot "bin\uv.exe"
if (-not (Test-Path $UvExe)) {
    Write-Error "bin\uv.exe not found in bundle. Bundle is corrupt."
    exit 1
}

$SourceDir = Join-Path $BundleRoot "source"
if (-not (Test-Path $SourceDir)) {
    Write-Error "source\ directory not found in bundle. Bundle is corrupt."
    exit 1
}

# 1. Sync Python dependencies into source\.venv using the bundled uv.
Write-Host "[1/3] Installing Python dependencies into source\.venv via bundled uv..."
Push-Location $SourceDir
try {
    & $UvExe sync
    if ($LASTEXITCODE -ne 0) { throw "uv sync failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}
Write-Host "      done."
Write-Host ""

# 2. Write .env with bundle-absolute paths.
$MemoryDb      = Join-Path $BundleRoot "data\memory.db"
$ExtensionsDir = Join-Path $BundleRoot "data\extensions"
# Pick the first .gguf file inside data\models\.
$ModelFile = Get-ChildItem -Path (Join-Path $BundleRoot "data\models") -Filter "*.gguf" | Select-Object -First 1
if (-not $ModelFile) {
    Write-Error "No .gguf file found in data\models. Bundle is corrupt."
    exit 1
}
$ModelPath = $ModelFile.FullName

$EnvPath = Join-Path $SourceDir ".env"
$EnvContent = @"
# Auto-generated by install.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm').
# NOTES_DIR is ignored by server.py (Windows never ingests) — placeholder only.
NOTES_DIR=C:\notes-placeholder
MEMORY_DB=$MemoryDb
EXTENSIONS_DIR=$ExtensionsDir
MODEL_PATH=$ModelPath

MEMORY_VECTOR_WEIGHT=0.5
MEMORY_TEXT_WEIGHT=0.5
MEMORY_MAX_RESULTS=10
MEMORY_MIN_SCORE=0.6
"@

Write-Host "[2/3] Writing $EnvPath..."
Set-Content -Path $EnvPath -Value $EnvContent -Encoding utf8
Write-Host "      done."
Write-Host ""

# 3. Register the MCP server in Claude Desktop's config.
Write-Host "[3/3] Registering MCP server in %APPDATA%\Claude\claude_desktop_config.json..."
Push-Location $SourceDir
try {
    & $UvExe run python -m setup.install_claude_desktop --uv "$UvExe" --project-dir "$SourceDir"
    if ($LASTEXITCODE -ne 0) { throw "install_claude_desktop failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}
Write-Host ""
Write-Host "Installation complete. Restart Claude Desktop to load the MCP server."
"""

INSTALL_BAT = r"""@echo off
rem install.bat - double-clickable wrapper around install.ps1.
rem Uses -ExecutionPolicy Bypass so the user doesn't need to change system policy.
powershell.exe -ExecutionPolicy Bypass -NoProfile -File "%~dp0install.ps1"
pause
"""

README_WINDOWS = """# local-rag — Windows bundle

This bundle contains everything you need to run the RAG MCP server on Windows:

- `source/` — project code (`server.py`, `ingest.py`, `setup/`, `pyproject.toml`, `uv.lock`)
- `data/memory.db` — pre-built index of the notes (built on the Mac side)
- `data/models/*.gguf` — local embedding model (~603 MB)
- `data/extensions/vector.dll` + `memory.dll` — SQLite extensions for Windows x64
- `bin/uv.exe` — portable [uv](https://github.com/astral-sh/uv) (no system install)
- `install.ps1` + `install.bat` — one-click installer
- `manifest.json` — SHA256 of every bundled file

## Prerequisites

- Windows 10/11 x64.
- Claude Desktop installed.
- ~1.5 GB free disk space.
- No admin rights needed.

## Install (one-time)

1. Unzip this bundle anywhere you like (e.g. `C:\\Users\\<you>\\rag-bundle\\`). Keep the folder — the installer writes paths that point inside it.
2. Double-click `install.bat`.
3. The installer will:
   - Run `uv sync` inside `source\\` to create a local `.venv` with FastMCP + deps.
   - Write `source\\.env` with bundle-absolute paths.
   - Merge a `local-rag` entry into `%APPDATA%\\Claude\\claude_desktop_config.json`
     (creating the file if missing, backing up any existing one to `.bak`).
4. Restart Claude Desktop.

In a conversation, the `search_memory` tool should now appear among available tools.

## Re-indexing

The bundled `memory.db` is a frozen snapshot from the Mac. To refresh the
notes, re-run `ingest.py` on the Mac, rebuild a new bundle with
`scripts/make_bundle.py`, and replace the old `data/memory.db` + (only if the
model changed) `data/models/*.gguf` on Windows.

## Moving the bundle

Paths in `source/.env` are absolute. If you move the bundle folder, re-run
`install.bat` so it regenerates `.env` and the config snippet with the new
location.

## Troubleshooting

- **Claude Desktop doesn't show the tool.** Check `%APPDATA%\\Claude\\logs\\`
  for MCP server errors. The `command` in `claude_desktop_config.json` must be
  the absolute path to `bin\\uv.exe` inside the bundle.
- **`load_extension is not allowed`.** Shouldn't happen with the bundled uv
  (it ships a Python built with extension loading). If it does, please report.
- **`sqlite_memory.dll is not a valid SQLite extension`.** Bundle is corrupt.
  Check `manifest.json` against actual file hashes.
"""


# ---------------------------------------------------------------------------
# Helpers.
# ---------------------------------------------------------------------------


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fp:
        for chunk in iter(lambda: fp.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _extract_from_tar_gz(archive: Path, suffix: str, out_path: Path) -> None:
    """Extract the first *suffix file from a tar.gz into out_path."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(archive, "r:gz") as tar:
        candidates = [m for m in tar.getmembers() if m.isfile() and m.name.lower().endswith(suffix)]
        if not candidates:
            names = ", ".join(m.name for m in tar.getmembers())
            raise RuntimeError(f"No *{suffix} in {archive.name}. Contents: {names}")
        member = min(candidates, key=lambda m: len(m.name))
        with tar.extractfile(member) as src, open(out_path, "wb") as dst:
            if src is None:
                raise RuntimeError(f"Failed to read {member.name} from {archive.name}")
            while True:
                buf = src.read(65536)
                if not buf:
                    break
                dst.write(buf)


def _extract_uv_exe(archive: Path, out_path: Path) -> None:
    """Pull uv.exe out of the Astral Windows zip."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(archive) as zf:
        candidates = [n for n in zf.namelist() if n.lower().endswith("uv.exe")]
        if not candidates:
            raise RuntimeError(f"uv.exe not found in {archive.name}. Contents: {zf.namelist()}")
        # Prefer the shortest-path entry (usually top-level uv.exe, not uvx.exe or a nested copy).
        member = min(candidates, key=len)
        with zf.open(member) as src, open(out_path, "wb") as dst:
            shutil.copyfileobj(src, dst)


# Text suffixes get DEFLATE compression; the rest stays STORED (already compressed).
_TEXT_SUFFIXES = {".py", ".toml", ".lock", ".md", ".json", ".ps1", ".bat", ".example", ".txt", ".cfg", ".ini"}


def _compression_for(name: str) -> int:
    if Path(name).suffix.lower() in _TEXT_SUFFIXES:
        return zipfile.ZIP_DEFLATED
    return zipfile.ZIP_STORED


# ---------------------------------------------------------------------------
# Bundle assembly.
# ---------------------------------------------------------------------------


def _gather_source_tree(staging: Path) -> list[Path]:
    """Copy source files/dirs into staging/source/ and return the list of files created."""
    src_out = staging / "source"
    src_out.mkdir(parents=True, exist_ok=True)

    copied: list[Path] = []

    for name in SOURCE_FILES:
        src = PROJECT_ROOT / name
        if not src.is_file():
            raise SystemExit(f"Missing source file: {src}")
        dst = src_out / name
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        copied.append(dst)

    for dirname in SOURCE_DIRS:
        src = PROJECT_ROOT / dirname
        if not src.is_dir():
            raise SystemExit(f"Missing source dir: {src}")
        for child in src.rglob("*"):
            if child.is_dir():
                continue
            if "__pycache__" in child.parts or child.suffix in {".pyc", ".pyo"}:
                continue
            rel = child.relative_to(PROJECT_ROOT)
            dst = src_out / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(child, dst)
            copied.append(dst)

    return copied


def _copy_data_artifacts(staging: Path) -> list[Path]:
    """Copy memory.db and the GGUF model into staging/data/."""
    copied: list[Path] = []

    memory_db = PROJECT_ROOT / "data" / "memory.db"
    if not memory_db.is_file():
        raise SystemExit(
            f"data/memory.db not found. Run ingest.py on the Mac first: "
            f"NOTES_DIR=<your-notes> uv run python ingest.py"
        )
    dst = staging / "data" / "memory.db"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(memory_db, dst)
    copied.append(dst)

    models_src = PROJECT_ROOT / "data" / "models"
    ggufs = sorted(models_src.glob("*.gguf"))
    if not ggufs:
        raise SystemExit(
            f"No .gguf model in {models_src}. Run setup/download_model.py first."
        )
    for gguf in ggufs:
        dst = staging / "data" / "models" / gguf.name
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(gguf, dst)
        copied.append(dst)

    return copied


def _download_windows_extensions(staging: Path) -> list[Path]:
    """Fetch Windows vector.dll + memory.dll from GitHub Releases into staging/data/extensions/."""
    ext_dir = staging / "data" / "extensions"
    ext_dir.mkdir(parents=True, exist_ok=True)

    key = ("windows", "x86_64")
    copied: list[Path] = []
    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)

        vector_url = VECTOR_URL_TEMPLATE.format(version=VECTOR_VERSION, asset=VECTOR_ASSETS[key])
        vector_archive = tmp / VECTOR_ASSETS[key]
        stream_download(vector_url, vector_archive, timeout=120.0)
        vector_dll = ext_dir / "vector.dll"
        _extract_from_tar_gz(vector_archive, ".dll", vector_dll)
        copied.append(vector_dll)

        memory_url = MEMORY_URL_TEMPLATE.format(version=MEMORY_VERSION, asset=MEMORY_ASSETS[key])
        memory_archive = tmp / MEMORY_ASSETS[key]
        stream_download(memory_url, memory_archive, timeout=120.0)
        memory_dll = ext_dir / "memory.dll"
        _extract_from_tar_gz(memory_archive, ".dll", memory_dll)
        copied.append(memory_dll)

    return copied


def _download_portable_uv(staging: Path, uv_version: str) -> Path:
    """Fetch uv.exe for Windows into staging/bin/uv.exe."""
    bin_dir = staging / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        url = UV_URL_TEMPLATE.format(version=uv_version, asset=UV_ASSET)
        archive = tmp / UV_ASSET
        stream_download(url, archive, timeout=120.0)
        uv_exe = bin_dir / "uv.exe"
        _extract_uv_exe(archive, uv_exe)
    return uv_exe


def _write_installers_and_readme(staging: Path) -> list[Path]:
    files: list[Path] = []

    ps1 = staging / "install.ps1"
    ps1.write_text(INSTALL_PS1, encoding="utf-8")
    files.append(ps1)

    # Write install.bat with CRLF line endings for Windows friendliness.
    bat = staging / "install.bat"
    bat.write_bytes(INSTALL_BAT.replace("\n", "\r\n").encode("utf-8"))
    files.append(bat)

    readme = staging / "README-windows.md"
    readme.write_text(README_WINDOWS, encoding="utf-8")
    files.append(readme)

    return files


def _build_manifest(staging: Path, bundle_name: str, uv_version: str) -> Path:
    entries = []
    for path in sorted(staging.rglob("*")):
        if path.is_dir():
            continue
        if path.name == "manifest.json":
            continue
        rel = path.relative_to(staging).as_posix()
        entries.append(
            {
                "path": rel,
                "size": path.stat().st_size,
                "sha256": _sha256(path),
            }
        )
    manifest = {
        "bundle": bundle_name,
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "uv_version": uv_version,
        "sqlite_vector_version": VECTOR_VERSION,
        "sqlite_memory_version": MEMORY_VERSION,
        "files": entries,
    }
    out = staging / "manifest.json"
    out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return out


def _zip_bundle(staging: Path, bundle_name: str, out_zip: Path) -> None:
    """Write staging/ into out_zip, nested under bundle_name/ as the top-level folder."""
    out_zip.parent.mkdir(parents=True, exist_ok=True)
    # allowZip64=True — the GGUF alone is 600 MB, total bundle easily fits in standard ZIP32
    # but larger datasets could push over 4 GB, so keep it safe.
    with zipfile.ZipFile(out_zip, "w", allowZip64=True) as zf:
        for path in sorted(staging.rglob("*")):
            if path.is_dir():
                continue
            rel = path.relative_to(staging).as_posix()
            arcname = f"{bundle_name}/{rel}"
            compression = _compression_for(rel)
            size_mb = path.stat().st_size / (1024 * 1024)
            print(
                f"  add {arcname} ({size_mb:.1f} MB, "
                f"{'DEFLATE' if compression == zipfile.ZIP_DEFLATED else 'STORED'})",
                file=sys.stderr,
            )
            zf.write(path, arcname=arcname, compress_type=compression)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a Windows distribution bundle")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DIST_DIR,
        help="Where to write the .zip (default: <project>/dist)",
    )
    parser.add_argument(
        "--uv-version",
        default=DEFAULT_UV_VERSION,
        help=f"Portable uv version to bundle (default: {DEFAULT_UV_VERSION})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing bundle zip with the same timestamped name",
    )
    args = parser.parse_args()

    bundle_name = "rag-bundle-" + datetime.now().strftime("%Y-%m-%d-%H%M")
    out_zip = args.output_dir / f"{bundle_name}.zip"

    if out_zip.exists() and not args.force:
        raise SystemExit(f"{out_zip} already exists. Re-run with --force to overwrite.")

    print(f"Building bundle: {bundle_name}", file=sys.stderr)
    print(f"Output:         {out_zip}", file=sys.stderr)
    print(f"uv version:     {args.uv_version}", file=sys.stderr)
    print("", file=sys.stderr)

    with tempfile.TemporaryDirectory(prefix="rag-bundle-") as staging_str:
        staging = Path(staging_str)

        print("Step 1/6: copying source tree...", file=sys.stderr)
        _gather_source_tree(staging)

        print("Step 2/6: copying data artifacts (memory.db + GGUF)...", file=sys.stderr)
        _copy_data_artifacts(staging)

        print("Step 3/6: downloading Windows extensions (vector.dll + memory.dll)...", file=sys.stderr)
        _download_windows_extensions(staging)

        print(f"Step 4/6: downloading portable uv {args.uv_version}...", file=sys.stderr)
        _download_portable_uv(staging, args.uv_version)

        print("Step 5/6: writing installers and README...", file=sys.stderr)
        _write_installers_and_readme(staging)

        print("Step 6/6: building manifest + zipping...", file=sys.stderr)
        _build_manifest(staging, bundle_name, args.uv_version)

        _zip_bundle(staging, bundle_name, out_zip)

    size_mb = out_zip.stat().st_size / (1024 * 1024)
    print("", file=sys.stderr)
    print(f"Bundle ready: {out_zip} ({size_mb:.1f} MB)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
